"""Business profile schema — structured output from the prompt factory.

The factory LLM generates a BusinessProfile JSON (data only).
The agent template is rendered FROM this data — the LLM never writes instructions.
"""
from __future__ import annotations

import re
from typing import Literal

from pydantic import BaseModel, Field, field_validator


class ServiceItem(BaseModel):
    """A single service offered by the fictitious company."""

    name: str = Field(..., min_length=2, max_length=80)
    price_installments: str | None = Field(
        default=None, max_length=60,
        description="Ex: 12x R$ 149 (None for businesses that don't do installments)"
    )
    price_cash: str = Field(
        ..., min_length=3, max_length=60, description="Ex: R$ 1.788 ou 'A partir de R$ 49'"
    )
    duration_or_scope: str = Field(
        ..., min_length=2, max_length=100, description="Ex: 60 min / 4 sessões"
    )
    highlight: bool = False

    @field_validator("price_installments")
    @classmethod
    def validate_installments_format(cls, v: str | None) -> str | None:
        """If provided, must look like Nx R$ X.XXX or similar."""
        if v is None:
            return v
        if not re.search(r"\d+x\s*R\$\s*[\d.,]+", v, re.IGNORECASE):
            # Graceful: if format doesn't match, just pass it through
            return v
        return v

    @field_validator("price_cash")
    @classmethod
    def validate_cash_format(cls, v: str) -> str:
        """Must contain R$ or be a valid description like 'Sob consulta'."""
        # Accept any non-empty string (restaurants may say "R$ 49" or "Sob consulta")
        return v


class FAQItem(BaseModel):
    """A single FAQ entry."""

    q: str = Field(..., min_length=5, max_length=200)
    a: str = Field(..., min_length=5, max_length=400)


class ObjectionItem(BaseModel):
    """A common objection and how to handle it."""

    objection: str = Field(..., min_length=5, max_length=200)
    guideline: str = Field(
        ..., min_length=10, max_length=400,
        description="How to counter WITHOUT discount or result promises"
    )


class BusinessProfile(BaseModel):
    """Structured profile of a fictitious company for the demo agent.

    Generated by the factory LLM (gpt-4.1-mini) and validated here.
    Used to render the fixed agent_template_v2.md into a system prompt.
    """

    agent_name: str = Field(
        ..., min_length=2, max_length=30,
        description="Brazilian first name, friendly"
    )
    company_name: str = Field(
        ..., min_length=3, max_length=60,
        description="Fictitious company name for this niche"
    )
    city: str = Field(
        ..., min_length=3, max_length=50,
        description="Brazilian city (medium/large)"
    )
    tagline: str = Field(
        ..., min_length=5, max_length=120,
        description="One-liner positioning"
    )
    services: list[ServiceItem] = Field(
        ..., min_length=3, max_length=10,
        description="3 to 10 services/products/menu items with realistic prices"
    )
    qualification_extra_question: str = Field(
        default="", max_length=200,
        description="One niche-specific qualification question (optional in v3)"
    )
    faq: list[FAQItem] = Field(
        ..., min_length=5, max_length=5,
        description="Exactly 5 FAQ items"
    )
    common_objections: list[ObjectionItem] = Field(
        ..., min_length=3, max_length=3,
        description="Exactly 3 objection handlers"
    )
    tone_notes: str = Field(
        ..., min_length=5, max_length=300,
        description="2-3 adjectives or short description of tone"
    )
    opening_message: str = Field(
        ..., min_length=10, max_length=160,
        description="First message from agent (greeting + hook)"
    )
    suggestions: list[str] = Field(
        ..., min_length=3, max_length=3,
        description="3 realistic first messages a client would send"
    )

    @field_validator("agent_name")
    @classmethod
    def name_is_capitalized(cls, v: str) -> str:
        return v.strip().title()

    @field_validator("company_name")
    @classmethod
    def company_name_stripped(cls, v: str) -> str:
        return v.strip()
